[toolchain]
anchor_version = "0.31.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
orbital_vault = "8aor5jUiu4irhm6MKjWSXTPq8JECXwZY4oJjRxSAuGPr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
